config/routes.rb
Rails.application.routes.draw do

  
  root 'users#home'
  
  # Omniauth Routes
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  resources :users, only: [:show, :edit, :update, :destroy] 

  get "/home" => "users#home", as: "home"
  
  # Clearance routes
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/start" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  
  # Games routes
  resources :games, only: [:show, :index]

  # Games rate refresher routes
  post '/refresh_fd_rates' => 'games#refresh_fixed_depoits_rates'
  post '/refresh_ut_rates' => 'games#refresh_unit_trust_rates'
  post '/refresh_s_rates' => 'games#refresh_stock_rates'
  post '/users/profile' => ''

  # Transaction routes
  resources :transactions, only: [:create, :show, :index]

  # Profile routes
  resources :profiles, except: [:edit, :destroy]
  

end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  validates :name, presence: {message: "Please enter your full name."}
  validates :email, presence: {message: "Please enter your email address."}, format: {with: /.+@.+\..+/i, message: "Please enter a valid email address."}
  # validates :password, presence: {message: "Please enter a password."}
  validates :nickname, length: {maximum: 12}

  has_many :authentications, dependent: :destroy
  has_many :profiles, dependent: :destroy

  def self.create_with_auth_and_hash(authentication,auth_hash)
    create! do |u|
      u.name = auth_hash[:extra][:raw_info][:name]
      u.email = auth_hash[:extra][:raw_info][:email]
      u.encrypted_password = SecureRandom.hex(10)
      u.authentications<<(authentication)
    end
  end

  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end

  def password_optional?
    true
  end
end

app/controllers/clearance/users_controller.rb
class Clearance::UsersController < Clearance::BaseController
  if respond_to?(:before_action)
    before_action :redirect_signed_in_users, only: [:create, :new]
    skip_before_action :require_login, only: [:create, :new], raise: false
    skip_before_action :authorize, only: [:create, :new], raise: false
  else
    before_filter :redirect_signed_in_users, only: [:create, :new]
    skip_before_filter :require_login, only: [:create, :new], raise: false
    skip_before_filter :authorize, only: [:create, :new], raise: false
  end

  def new
    @user = user_from_params
    render template: "users/new"
  end

  def create
    @user = User.new(permit_params)
    if @user.save
      sign_in @user
      @profile = @user.profiles.new(profile_params)
      @profile.current_balance = 0.2*(params[:profile][:financial_goal]).to_f 
      @profile.save
      redirect_to edit_user_path(@user)
    else
      flash[:danger] = @user.errors.values.flatten.last
      respond_to do |format|
        format.html { redirect_to sign_in_path }
        format.js
      end
    end
  end

  private

  def avoid_sign_in
    warn "[DEPRECATION] Clearance's `avoid_sign_in` before_filter is " +
      "deprecated. Use `redirect_signed_in_users` instead. " +
      "Be sure to update any instances of `skip_before_filter :avoid_sign_in`" +
      " or `skip_before_action :avoid_sign_in` as well"
    redirect_signed_in_users
  end

  def redirect_signed_in_users
    if signed_in?
      redirect_to Clearance.configuration.redirect_url
    end
  end

  def url_after_create
    Clearance.configuration.redirect_url
  end

  def user_from_params
    email = user_params.delete(:email)
    password = user_params.delete(:password)

    Clearance.configuration.user_model.new(user_params).tap do |user|
      user.email = email
      user.password = password
    end
  end

  def user_params
    params[Clearance.configuration.user_parameter] || Hash.new
  end

  def permit_params
    params.require(:user).permit(:name, :email, :nickname, :birthday, :password)
  end

  def profile_params
    params.require(:profile).permit(:financial_goal)
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
	before_action :set_user_and_profile, except: :home
	before_action :check_user, only: :edit

	def home
		if current_user.nil?
			redirect_to sign_in_path
    elsif current_user.nickname.nil? || current_user.birthday.nil?
      redirect_to edit_user_path(current_user)
		else
      redirect_to games_path
    end
	end

	def show
	end

	def edit
	end

  def update
    if @user.update_attributes(user_params)
      @profile.update_attributes(financial_goal: profile_params[:financial_goal][/\d+/])
      redirect_to home_path
    else
     redirect_to edit_user_path(@user), flash:{danger: @user.errors.values.first}
    end
  end

  private

  def check_user
    unless @user == current_user
      redirect_to sign_in_path, flash:{danger: "You are not authorized to view that page."}
    end
  end

  def set_user_and_profile
    @user = User.find(params[:id])
    @profile = @user.profiles.find_by(active: true)
  end

  def user_params
    params.require(:user).permit(:name, :email, :nickname, :birthday, :password)
  end


  def profile_params
    params.require(:profile).permit(:financial_goal)
  end

  
end

app/views/users/_form.html.erb
<%= form_for User.new, remote: true do |form| %>		
	<div class="text-field">
		<%= form.text_field :name, placeholder: "Your full name" %>
	</div>

	<div class="text-field">
	  <%= form.text_field :email, type: 'email', placeholder: "Your email address" %>
	</div>

	<div class="password-field">
	  <%= form.password_field :password, placeholder: "Create a password" %>
	</div>

	<%= button_to "Get Started", sign_up_path, class: "btn", id: "get-started-button" %>

<div class="other-links">
  <button class="loginBtn loginBtn-facebook">
    <a href="/auth/facebook">Continue with Facebook</a>
  </button>
  <button class="loginBtn loginBtn-google">
    <a href="/auth/google_oauth2">Continue with Google</a>
  </button>
  <br>
	<button type="button" class="btn btn-link" id="sign-in-email">Already have an account?</button>
<% end %>

app/views/users/edit.html.erb
<div class="sign-up-questions">
	<%= form_for @user, id: "edit-user-form" do |form| %>
		<div id="nickname-question">
			<p>How shall we address you?</p>
			<%= form.text_field :nickname, id: "nickname-input" %>
			<button type="button" class="btn btn-link" id="sign-up-continue">></button>
		</div>
		<div id="birthday-question">
			<p>When is your birthday?</p>
			<%= form.date_field :birthday, id: "birthday-input" %>
			<button type="button" class="btn btn-link" id="sign-up-continue-2">></button>
		</div>
		<div id="financial-goal-question">
			<p>Reconfirm your financial goal.</p>
			<input type="text" id="financial-goal-input" name="profile[financial_goal]" value="RM <%= @profile.financial_goal %>">
			<br>
			<%= form.submit "start" %>		
		</div>
	<% end %>
</div>

app/views/users/home.html.erb
hello

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to "Login with Facebook", '/auth/facebook' %>
      <%= link_to "Login with Google", "/auth/google_oauth2" %>
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
hello