config/routes.rb
Rails.application.routes.draw do

  
  root 'users#home'
  
  # Omniauth Routes
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  resources :users, only: [:show, :edit, :update, :destroy] 

  get "/home" => "users#home", as: "home"
  
  # Clearance routes
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/start" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  
  # Games routes
  resources :games, only: [:show, :index]

  # Games rate refresher routes
  post '/refresh_fd_rates' => 'games#refresh_fixed_depoits_rates'
  post '/refresh_ut_rates' => 'games#refresh_unit_trust_rates'
  post '/refresh_s_rates' => 'games#refresh_stock_rates'
  post '/users/profile' => ''

  # Transaction routes
  resources :transactions, only: [:create, :show, :index]

  # Profile routes
  resources :profiles, except: [:edit, :destroy]
  

end

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> fade in">
    <a href="#" class="close" data-dismiss="alert" aria-label="close" style="">&times;</a><%=h value %>
  </div>
<%end%>

app/views/layouts/_navbar.html.erb
<div id="mySidenav" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <div class="logo-nav">
    <a href="#" id="logo-nav">
      <div id="wrap-nav">
        <div id="left-lg">ou</div>
        <div id="mid-lg">RM</div>
        <div id="right-lg">oney</div>
      </div>
    </a>
  </div>
  <%= link_to "Edit Profile", edit_user_path(current_user.id) %>
  <%= link_to "Home", games_path %>
  <a id="financial_product">Financial Product</a>
  <div id="nav_dropdown" style="display:none">
	  <%= link_to "Fixed Deposit", game_path("fixed_deposit") %>
	  <%= link_to "Unit Trust", game_path("unit_trust") %>
	  <%= link_to "Stock", game_path("stock") %>
  </div>
  <%= link_to "Summary", profile_path(current_user.id) %>
  <%= link_to "Sign Out", sign_out_path, method: :delete %>
</div>

<div onclick="openNav()" id="open-navbar-button">></div>

<script>
	$('#financial_product').click(function(){
		$('#nav_dropdown').toggle("slow");
	})

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ouRMoney</title>

  <!-- <link href="/app/favicon.ico" rel="icon" type="image/x-icon" /> -->
  <link href='https://fonts.googleapis.com/css?family=Righteous' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

   <meta name="viewport" content="width=device-width, initial-scale=1.0">  
  <script src="https://js.braintreegateway.com/v2/braintree.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Comfortaa|Raleway" rel="stylesheet">
    <!--Required additions for chartkick -->
    <%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>

</head>
<body>
  <div class="container-fluid" id="summary-container">
    <div id="main">
      <% if signed_in? %>
        <%= render 'layouts/navbar' %>
      <% end %>
    
      <div id="flashes">
        <%= render 'layouts/flashes' %>
      </div>
      <%= yield %>
    </div>
  </div>
</body>
</html>